routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\TweetController;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware('auth')->group(function(){
    Route::get('/tweet', 'TweetController@index')->name('home');
    Route::post('/tweet','TweetController@store');

});

//Route::get('/home', 'HomeController@index')->name('home');

app/Tweet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Tweet extends Model
{
    protected $guarded = [];

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getAvatarAttribute()
    {
        return "https://i.pravatar.cc/40?u=". $this->email;
    }

    public function timeline(){
        //include all of this user tweet
        //and tweets of everyone they follow

        $friends = $this->follows()->pluck('id');

        //in descending order
        return Tweet::whereIn('user_id', $friends)
                ->orWhere('user_id', $this->id)
                ->latest()
                ->get();
    }

    public function tweets()
    {
        return $this->hasMany(Tweet::class);
    }

    public function follow(User $user)
    {
        return $this->follows()->save($user); //don't understand how it works :(
    }

    public function follows()
    {
        return $this->belongsToMany(User::class, 'follows', 'user_id', 'following_user_id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TweetController.php
<?php

namespace App\Http\Controllers;
use App\Tweet;
use Illuminate\Http\Request;

class TweetController extends Controller
{
    public function index()
    {
        return view('tweets.index', [
            'tweets' => auth()->user()->timeline()
        ]);
    }

    public function store()
    {
        $validatedAttribute = request()->validate(['body'=> 'required|max:250']);
        Tweet::create([
            'user_id'=> auth()->id(),
            'body'=> $validatedAttribute['body']
        ]);

        return redirect('/tweet');
    }

}

resources/views/_friends_list.blade.php
<h3 class="font-bold text-xl mb-4">Follows</h3>

<ul>
    @foreach(auth()->user()->follows as $user)
        <li class="mb-2">
            <div class="flex items-center text-sm">
                <img src="{{$user->avatar}}" alt="your avatar" class="rounded-full mr-2">
                {{$user->name}}
            </div>
        </li>
    @endforeach
</ul>

resources/views/_publish_tweet_panel.blade.php
    <div class="border border-blue-400 rounded-lg px-8 py-6 mb-8">
        <form action="/tweet" method="POST">
            @csrf
            <textarea name="body" id="" cols="30" class="w-full" placeholder="What's up bro?"></textarea>
            <hr class="my-4">

            <footer class="flex justify-between">
                <img src="{{auth()->user()->avatar}}" alt="your avatar" class="rounded-full mr-2">
                <button type="submit" class="bg-blue-500 rounded-lg shadow py-2 px-2 text-white">tweet now</button>
            </footer>

        </form>

        @error('body')
            <p class="text-sm text-red-500 py-2">{{$message}}</p>
        @enderror
    </div>

resources/views/_sidebar_links.blade.php
<ul>
    <li class="font-bold text-lg mb-4 block">
        <a href="/">Home</a>
    </li>

    <li class="font-bold text-lg mb-4 block">
        <a href="/explore">Explore</a>
    </li>

    <li class="font-bold text-lg mb-4 block">
        <a href="#">Notifications</a>
    </li>

    <li class="font-bold text-lg mb-4 block">
        <a href="#">Messages</a>
    </li>

    <li class="font-bold text-lg mb-4 block">
        <a href="#">Bookmarks</a>
    </li>

    <li class="font-bold text-lg mb-4 block">
        <a href="#">Lists</a>
    </li>

    <li class="font-bold text-lg mb-4 block">
        <a href="#">Profile</a>
    </li>

    <li class="font-bold text-lg mb-4 block">
        <a href="#">More</a>
    </li>

</ul>

resources/views/_tweet.blade.php
<div class="flex p-4 border-b border-b-gray-400">
    <div class="mr-2 flex-shrink-0">
        <img src="{{$tweet->user->avatar}}" alt="" class="rounded-full mr-2">
    </div>

    <div>
        <h5 class="font-bold mb-4">{{$tweet->user->name}}</h5>
        <p class="text-sm">
            {{$tweet->body}}
        </p>
    </div>

</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!--styles(tailwindcss)-->
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div id="app">
        <section class="px-8 py-4 mb-6">
            <header class="container mx-auto">
                <h1>
                    <img src="/img/logo.svg" alt="Tweety">
                </h1>
            </header>
        </section>


        <section class="px-8">
            <main class="container mx-auto">
                @yield('content')
            </main>
        <section>
    </div>
</body>
</html>

resources/views/tweets/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="lg:flex lg:justify-between" >
        <div class="lg:w-32">
            @include('_sidebar_links')
        </div>

        <div class="lg:flex-1 lg:mx-10" style="max-width: 700px">
            @include('_publish_tweet_panel')

            <div class="border border-gray-300 rounded-lg">
            @foreach($tweets as $tweet)
                @include('_tweet')
            @endforeach
            </div>
        </div>

        <div class="lg:w-1/6 bg-blue-200 rounded-lg p-4">
            @include('_friends_list')
        </div>
    </div>
@endsection